### ISSUE TITLE
Problem with singularity

### ISSUE THREAD

**Issue by JihedC** [ftabaro/rrbs-pipeline#5]
Hi @ftabaro ,

Thank you for your pipeline it seems very nice. I would like to try it but I have some issue with singularity.

I believe that before running the pipeline I need to perform a pull of the singularity container with:
`singularity pull library://ftabaro/default/methylsnake`

However when I do it I get the following error message: 
`ERROR: pull is only supported for shub URIs`

I use singularity 3.6.1.

I have found your container [here](https://cloud.sylabs.io/library/_container/5f579eb2b1793638c1138bfa). But the pull command throws the same error. 

I don't have administrator rights on the cluster computer I work on so the commands to compile the container won't work either. 

```
sudo singularity build base.sif Singularity.base
sudo singularity build methylkit.sif Singularity.methylkit
```

Do you have suggestions to solve this issue? Can I install all the required packages via conda? 

Thanks for your help!

**Comment by ftabaro** [comment]
Hello, thanks for your message. 

I have now fixed the tag on the library. You should be able to pull with `singularity pull library://ftabaro/default/methylsnake`.

Let me know if you encounter more errors.

**Comment by JihedC** [comment]
Hi,

Thanks for the quick reply. Unfortunately it did not solve the problem. Here are the step to reproduce the problem :
```
> module load container/singularity/3.6.1

> singularity pull library://ftabaro/default/methylsnake

ERROR: pull is only supported for shub URIs
```

I think the problem is within the url but I don't know how to solve it. Would it work it I add the conda environment to each snakemake rule?

**Comment by ftabaro** [comment]
You have two options:
1. figure out why the `library://` points to Singularity Hub (which has a dedicated `shub://` type of URI). You can get this info by using the `singularity remote` command to list and manage remote endpoints. Singularity supports per-user configuration so you should be able to override the defaults of your cluster.
2. edit the Snakefile to use conda envs. If you test it and it works, then you can submit a pull request and I can update this repo. However, the `run_snakemake.sh` will have to be updated in order to handle both execution with Singularity and Conda.

**Comment by JihedC** [comment]
Okay I found the solution. Somehow my command:
`module load container/singularity/3.6.1` was loading singularity version 2.4. I have loaded a newer version of singularity and the pull now worked. 

I have another question concerning the configuration file. Do you prefer that I close this issue and open a new one?

Thanks for your help! This is one of the best documentation I have seen for a snakemake pipeline :)

**Comment by ftabaro** [comment]
That's good to hear! Please open a new issue.
